#!/bin/bash
geth --identity "PetClinicTestNode" \
  --rpc --rpcport 7545 --rpccorsdomain "*" \
  --datadir ./ --port 30303 --nodiscover \
  --rpcapi eth,net,web3,personal --networkid 5777 --maxpeers 0 \
  --allow-insecure-unlock console
