#!/bin/bash
geth --identity "PetClinicTestNode" \
  --rpc --rpcport 8080 --rpccorsdomain "*" \
  --datadir . --port 30303 --nodiscover \
  --rpcapi eth,net,web3,personal --networkid 1999 --maxpeers 0 \
  --verbosity 6 init ./CustomGenesis.json
